name       : vidcutter
version    : 6.0.0
release    : 1
source     :
    - https://github.com/ozmartian/vidcutter/archive/6.0.0.tar.gz : c09be7eceaf42ff7211fe3b8125279c4fec7f7d251d272b61d579e426bd4e2c2
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : A modern, simple to use, constantly evolving and hella fast MEDIA CUTTER and JOINER with frame-accurate SmartCut technology and Qt5, libmpv, FFmpeg and MediaInfo powering the backend.
description: |
    A modern, simple to use, constantly evolving and hella fast MEDIA CUTTER and JOINER with frame-accurate SmartCut technology and Qt5, libmpv, FFmpeg and MediaInfo powering the backend.
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(mpv)
    - pkgconfig(python3)
    - python3-qt5
    - python-opengl
rundeps     :
    - mediainfo
    - python3-qt5
    - python-opengl
setup      : |
    %python3_setup
install    : |
    %python3_install
