name       : vidcutter
version    : 6.0.5.1
release    : 6
source     :
    - https://github.com/ozmartian/vidcutter/archive/refs/tags/6.0.5.1.tar.gz : c6374eaedb845f9e580e555dd12c1db1cf2ffa28d3756b08e2ae28c1a4cd4a96
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : A modern, simple to use, constantly evolving and hella fast MEDIA CUTTER and JOINER with frame-accurate SmartCut technology and Qt5, libmpv, FFmpeg and MediaInfo powering the backend.
description: |
    A modern, simple to use, constantly evolving and hella fast MEDIA CUTTER and JOINER with frame-accurate SmartCut technology and Qt5, libmpv, FFmpeg and MediaInfo powering the backend.
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(mpv)
    - pkgconfig(python3)
    - python3-qt5
    - python-opengl
rundeps    :
    - mediainfo
    - python3-qt5
    - python-opengl
setup      : |
    %python3_setup
install    : |
    %python3_install
